Threshold_of_CollisionDetection: 0.1
Modified_DH_d1: 0.267
Modified_DH_d4: 0.3425
Modified_DH_d6: 0.097
Modified_DH_a3: 0.28948866
Modified_DH_a4: 77.5
Modified_DH_a6: 76
Modified_DH_T2offset: -1.3849179
Modified_DH_T3offset: 1.3849179